apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/description: Wikijs instance
  name: wikijs
  namespace: k8s-demo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
    type: RollingUpdate
  selector:
    matchLabels:
      app: wikijs
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      containers:
      - image: lscr.io/linuxserver/wikijs:latest
        imagePullPolicy: Always
        name: wikijs
        envFrom:
        - configMapRef:
            name: wikijs-cm
        env:
        - name: TZ
          value: "Asia/Kuala_Lumpur"
        ports:
        - containerPort: 3000
          name: wikijs-port
          protocol: TCP
        volumeMounts:
        - name: wikijs-config
          mountPath: /config
        - name: wikijs-data
          mountPath: /data
      volumes:
      - name: wikijs-config
        hostPath:
          path: /opt/local-pv/wikijs/config
      - name: wikijs-data
        hostPath:
          path: /opt/local-pv/wikijs/data
      nodeSelector:
        kubernetes.io/hostname: cthulhu0

