apiVersion: v1
kind: Service
metadata:
 name: wikijs-np
 namespace: k8s-demo
spec:
 type: NodePort
 selector:
  app: wikijs
 ports:
  - name: wikijs-np
    port: 3000
    targetPort: wikijs-port
    nodePort: 32002

