apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/description: Redis instance
  name: redis
  namespace: k8s-demo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
    type: RollingUpdate
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - image: docker.io/redis:latest
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379
          name: redis-port
          protocol: TCP
        volumeMounts:
        - name: redis-config
          mountPath: /usr/local/etc/redis/redis.conf
          subPath: redis.conf
        - name: redis-datadir
          mountPath: "/var/lib/redis"
        command: ["redis-server"]
        args: ["/usr/local/etc/redis/redis.conf", "--requirepass $(REDIS_PASSWORD)"]
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
      - name: redis-datadir
        hostPath:
          path: /opt/local-pv/redis
      nodeSelector:
        kubernetes.io/hostname: cthulhu0

