apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: k8s-demo
  annotations:
    field.cattle.io/description: redis.conf
data:
  redis.conf: |
    protected-mode yes
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    supervised no
    loglevel notice
    databases 5
    always-show-logo yes
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    rdb-del-sync-files no
    acllog-max-len 128
    appendonly yes
    appendfsync everysec
    dir /var/lib/redis
    lua-time-limit 5000
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    latency-monitor-threshold 0 
    loglevel verbose
    logfile /dev/stderr
 
