apiVersion: v1
kind: Service
metadata:
 name: redis-np
 namespace: k8s-demo
spec:
 type: NodePort
 selector:
  app: redis
 ports:
  - name: redis-nodeport
    port: 6379
    targetPort: redis-port
    nodePort: 32003
