apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-gitea-pvc
  annotations:
    field.cattle.io/description: Gitea PVC
  namespace: default
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

