apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/description: Yet another local git instance
  name: local-gitea
  namespace: k8s-demo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
    type: RollingUpdate
  selector:
    matchLabels:
      app: local-gitea
  template:
    metadata:
      labels:
        app: local-gitea
    spec:
      containers:
      - image: gitea/gitea:latest-rootless
        imagePullPolicy: Always
        name: local-gitea
        ports:
        - containerPort: 3000
          name: web
          protocol: TCP
        - containerPort: 2222
          name: ssh
          protocol: TCP
        volumeMounts:
          - name: vol
            mountPath: "/data"
          - name: data
            mountPath: "/var/lib/gitea"
          - name: config
            mountPath: "/etc/gitea"
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: local-gitea-vol
        - name: data
          persistentVolumeClaim:
            claimName: local-gitea-data
        - name: config
          persistentVolumeClaim:
            claimName: local-gitea-config

