apiVersion: v1
kind: Service
metadata:
 name: local-gitea-np
 namespace: k8s-demo
spec:
 type: NodePort
 selector:
  app: local-gitea
 ports:
  - name: web
    port: 3000
    targetPort: web
    nodePort: 32000
  - name: ssh
    port: 2222
    targetPort: ssh
    nodePort: 32001

